### ISSUE TITLE
Excel parser handle regular expression sheet name

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#23]
Currently you can only load one excel sheet at a time with the xls/xlsx parser. It would be great if you could load multiple resources at a time by entering a regular expression for the sheet name. For example `*` would load all of the sheets.

My suggestion would be that if the `name` parameter is blank, each resource is named after the sheet name. A nice addition would be the ability to input a string of comma separated names into the `name` parameter that will match up with the resources captured by the regular expression (assuming the sheets are loaded in the order that they show on a normal excel reader).

Thanks for all of your work!

**Comment by cschloer** [comment]
Hey @roll is it okay if I reorder the priority on the OKF Pilot board? The top two (https://github.com/BCODMO/frictionless-usecases/issues/21 and https://github.com/BCODMO/frictionless-usecases/issues/18) are pretty low prioity for us.

**Comment by roll** [comment]
@cschloer 
sure, please do

**Comment by roll** [comment]
@cschloer 
@adyork 
So the current situation with this one:
- the solution was developed by me and it works - https://github.com/datahq/dataflows/pull/110
- it will not be accepted because it can be really ineffective due to how `tabulator` works (and I agree that it's more like a hack)

So we can do regarding BCO-DMO:
- using the written code in the custom BCO-DMO processor
- using preprocessor (within UI code I guess) proposed here - https://github.com/datahq/dataflows/pull/110#issuecomment-535501938 - creating needed `load` steps automatically

**Comment by cschloer** [comment]
:+1: thanks @roll !
